# Generated by Django 5.0.3 on 2024-03-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='show_description',
            new_name='short_description',
        ),
    ]
